application: pi-sync
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static/
  static_dir: static/
  login: required

- url: /api/.*
  script: apphandlers.app
  
- url: /.*
  script: apphandlers.app
  login: required

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest